name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Connexion à DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construire l'image Docker
      run: docker build -t dieynaba127/my-http-server:latest .

    - name: Pousser l'image sur DockerHub
      run: docker push dieynaba127/my-http-server:latest
